# Setup
title: HM-Easyumzug
tagline: Einfach umziehen in Frankfurt am Main
url: hm-easuymzug.de
paginate: 1
baseurl: ""
permalink: pretty
description: "Einfach umziehen in Frankfurt am Main mit dem Familienunternehmen HM-Easyumzug. Wir bieten Full-Service Umzüge aus einer Hand - keine Subunternehmer. Google Bewertung: 5 Sterne. Persönliche*r Umzugsmanager*in, top Versicherung und freundliches und professionelles Team!"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  #- jekyll-autoprefixer

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author: 
  name: Maryam Hemati
  url: hm-easyumzug.de
  email: info@hm-easyumzug.de
  instagram: hmeasyumzug

# Custom vars
version: 

social:
  name: HM-Easyumzug
  links:
    - https://www.facebook.com/pages/category/Moving---Storage-Service/HM-Easyumzug-106265624347586/
    - https://www.instagram.com/hmeasyumzug/

logo: /assets/logo/logo-hm-easyumzug-blue-bg.png