# Setup
title: HM-Easyumzug
tagline: Einfach umziehen in Frankfurt am Main
url: https://hm-easuymzug.de
paginate: 1
baseurl: ""
permalink: pretty
description: "Einfach umziehen mit dem Frankfurter Familienunternehmen HM-Easyumzug. Persönliche Umzugsberatung, höchste Qualität und ein 5 Sterne Team!"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  #- jekyll-autoprefixer

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author: 
  name: Maryam Hemati
  url: hm-easyumzug.de
  email: info@hm-easyumzug.de

# Custom vars
version: 


social:
  name: Maryam Hemati
  links:
    - https://www.facebook.com/pages/category/Moving---Storage-Service/HM-Easyumzug-106265624347586/
    - https://www.instagram.com/hmeasyumzug/
